# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    ports:
      - 4321:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
