version: '3.1'

services:
    postgres:
        image: postgres:11
        ports:
            - 5432:5432
        restart: unless-stopped
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: db
        networks:
            - net

    # http://localhost:5050
    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: user@mail.com
            PGADMIN_DEFAULT_PASSWORD: pass
        ports:
            - 5050:80
        networks:
            - net

    mongo:
        image: mongo:latest
        restart: unless-stopped
        ports:
            - 27017:27017
        networks:
            - net

    # http://localhost:8081
    mongo-express:
        image: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
        networks:
            - net

    redis:
        image: redis:latest
        restart: unless-stopped
        command: ['redis-server', '--appendonly', 'yes']
        ports:
            - 6379:6379
        networks:
            - net

    # http://localhost:8082
    phpredisadmin:
        image: erikdubbelboer/phpredisadmin
        restart: unless-stopped
        ports:
            - 8082:80
        environment:
            REDIS_1_HOST: redis
            REDIS_1_PORT: 6379
        networks:
            - net

networks:
    net:
        driver: bridge
