version: '3.1'

services:

  postgres:
    image: postgres:latest
    ports:
      - 4321:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - net

  mongo-gui:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    networks:
      - net

  redis:
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    networks:
      - net

  redis-gui:
    image: erikdubbelboer/phpredisadmin
    restart: unless-stopped
    ports:
      - 6380:80
    environment:
      REDIS_1_HOST: redis
      REDIS_1_PORT: 6379
    networks:
      - net

networks:
  net:
    driver: bridge
